var home = "This is home Page. <br>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsam beatae iure consectetur quos, veniam nulla cumque rem saepe esse in explicabo laudantium commodi alias accusamus suscipit rerum ducimus asperiores natus nostrum modi? Nesciunt, iste voluptatem aut incidunt excepturi quia ipsum aliquam impedit doloribus eos, libero atque praesentium veniam perspiciatis alias, quo repellendus rerum commodi est in odit facere voluptatum accusamus quae. Fuga soluta nulla architecto rerum facilis aperiam quo quisquam iure maiores animi quae, tempore reiciendis id dolorem magnam facere reprehenderit nihil minima quod aliquid, ullam libero omnis beatae consectetur. Incidunt pariatur veniam animi placeat officiis, voluptate beatae quod eius hic distinctio iusto consequatur illum quam ea minima ullam tempore repudiandae ex voluptatibus aliquam non nulla? Tempore, enim earum? Obcaecati inventore recusandae id, vero dignissimos nulla cumque excepturi eveniet non temporibus quas asperiores perspiciatis placeat animi quasi voluptas ratione, sequi possimus, velit deleniti culpa illo! Explicabo nesciunt iure libero impedit ullam, itaque suscipit est dolor? Dignissimos officiis sequi ad necessitatibus qui, corrupti minima praesentium animi autem quis, aspernatur tempora architecto magnam possimus maiores id velit voluptates. Praesentium dolore commodi explicabo enim voluptatibus nihil earum et odio aspernatur, cumque omnis sit quo iste illo ab, excepturi, odit iure? Soluta, excepturi perferendis."

var contact = "This is contact Page. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ab iure inventore possimus maiores quaerat, temporibus enim itaque at ipsa, commodi deleniti velit molestias dolor tempore. Aliquam dolores quos sed maxime corrupti dolorem rerum labore, vero perspiciatis placeat officia fugiat magnam tempora ullam sint neque accusamus qui odio asperiores suscipit dignissimos eligendi dolore necessitatibus dicta. Mollitia recusandae nemo autem quo veritatis, error nisi! Facere possimus nam deleniti ea dignissimos quod veniam perferendis tenetur expedita quos natus temporibus, debitis impedit labore ducimus consequatur quis. Autem distinctio eum excepturi, accusantium, similique facere quam quod recusandae at voluptatum delectus alias quasi consectetur sit dolor!"

var about = "This is about page Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ab iure inventore possimus maiores quaerat, temporibus enim itaque at ipsa, commodi deleniti velit molestias dolor tempore. Aliquam dolores quos sed maxime corrupti dolorem rerum labore, vero perspiciatis placeat officia fugiat magnam tempora ullam sint neque accusamus qui odio asperiores suscipit dignissimos eligendi dolore necessitatibus dicta. Mollitia recusandae nemo autem quo veritatis, error nisi! Facere possimus nam deleniti ea dignissimos quod veniam perferendis tenetur expedita quos natus temporibus, debitis impedit labore ducimus consequatur quis. Autem distinctio eum excepturi, accusantium, similique facere quam quod recusandae at voluptatum delectus alias quasi consectetur sit dolor!"

module.exports = {
    homeContent : home,
    aboutContent: about,
    contactContent: contact
}